### PR TITLE
more rules

### PR DESCRIPTION
**Pull request by r3l1c7**
The problem is there is an error loading some of them, everything seems right, do you know what's causing this on the project load into burp so we can get some new rules?

### CODE REVIEW

**Comment by augustd** [comment]
@r3l1c7 Thanks for the addition of new rules! However it looks like your submission also removed quite a few rules as well. Can you please do a fresh pull and add your new rules to the end of match-rules.tab? 

Also can you please provide some examples of strings that match these rules that we can use for testing? Those can be added to [src/test/resources/burp/testResponse.txt](https://github.com/augustd/burp-suite-error-message-checks/blob/master/src/test/resources/burp/testResponse.txt)

**Comment by r3l1c7** [comment]
> @r3l1c7 Thanks for the addition of new rules! However it looks like your submission also removed quite a few rules as well. Can you please do a fresh pull and add your new rules to the end of match-rules.tab?
> 
> Also can you please provide some examples of strings that match these rules that we can use for testing? Those can be added to [src/test/resources/burp/testResponse.txt](https://github.com/augustd/burp-suite-error-message-checks/blob/master/src/test/resources/burp/testResponse.txt)

Yeah, sorry about that, I used something to remove duplicates and I think it changed the order but not actually removed the old rules.

When I get a spare hour or two, I'll do a new pull and paste in some target test responses.

**Comment by floyd-fuh** [comment]
bump @r3l1c7

**Comment by augustd** [comment]
Replaced by #63

**Pull request closed without merging**
